apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: app
      hasuraService: custom
    name: app
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: app
      spec:
        containers:
        - image: hasura/hello-world:latest
          env:
          - name: PRODUCTION
            value: "true"
          - name: CLUSTER_NAME 
            value: {{ cluster.name }}
          - name: PAGE_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                key: page.access.token
                name: hasura-secrets
          - name: VERIFY_TOKEN
            valueFrom:
              secretKeyRef:
                key: verify.token
                name: hasura-secrets
          imagePullPolicy: IfNotPresent
          name: app
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: app
      hasuraService: custom
    name: app
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      app: app
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
